### ISSUE TITLE
Please use comments to explain main parts of the logic.

### ISSUE THREAD

**Issue by mittalgovind** [reachsachinhere/coding-practice#6]
The code should be self documented. Its very hard to understand why you are taking a step, otherwise.

**Comment by mittalgovind** [comment]
Please explain the collatz sequence program. I dont know what it is doing. it is just printing **20 9%** for every input. Also fix the issues that are present already also. If the issue is fixed, then close it too.

**Comment by reachsachinhere** [comment]
Updated collatz sequence program. 
It is giving correct answers. Check again.
